# The deliver file which lets you add the required metadata when 
# submitting your app to the App Store.

# 1
price_tier 0
# 2
app_review_information(
  first_name: "Ben",
  last_name: "Smith",
  phone_number: "+31622282567	",
  email_address: "benjaminsmith1981@gmail.com",
  demo_user: "N/A",
  demo_password: "N/A",
  notes: "No demo account needed"
)
# 3
submission_information({    
    export_compliance_encryption_updated: false,
    export_compliance_uses_encryption: false,
    content_rights_contains_third_party_content: false,
    add_id_info_uses_idfa: false
})
# 4
automatic_release false

# 5
app_icon './fastlane/metadata/AppIcon.png'
# 6
app_rating_config_path "./fastlane/metadata/itunes_rating_config.json"